### ISSUE TITLE
Listening issue - Windows 7 Web browsers

### ISSUE THREAD

**Issue by silverkorn** [xiph/Icecast-Server#11] opened 2017-03-08 20:05 UTC
Not sure if it's related with this issue https://github.com/xiph/Icecast-Server/issues/8 but listening to streams broadcasted by __Icecast 2.4.2__ is taking way too long before starting natively on any Web browsers on Windows 7. Note that audio players/tools such as FFplay and VLC works properly under this OS.

This issue doesn't seem to happen using an __Icecast 2.4.0 (KH branch)__ server.

Thanks!

**Comment by ePirat** [comment] 2017-03-09 21:31
This is not an issue with Icecast but sounds a lot like configuration specific. Note that you can try to use a bigger burst on connect in the Icecast config (remember to increase the overall buffer too).

**Comment by ePirat** [comment] 2017-03-09 21:33
And no, this is completely unrelated to #8, as that is about sending content to Icecast.

**Comment by ePirat** [comment] 2017-03-09 21:43
If it turns out that increasing burst will not help, please comment again here, and I'll have another look at it.

**Comment by silverkorn** [comment] 2017-03-10 15:33
This was already tested from 64k to 32k.
Did you have a chance to test on your end?

**Comment by ePirat** [comment] 2017-03-10 15:38
What do you mean by "from 64k to 32k"? That would be making the burst smaller, which is the wrong thing to do in this case, as you want a bigger buffer, so the browsers player buffer fills faster and playback starts faster.

**Comment by ePirat** [comment] 2017-03-10 15:46
And please provide a few more details:

- Which format are you streaming in?
- Which Bitrate or Quality?
- Which web browser(s) did you try this with?
- If possible, the url for the problematic stream

**Comment by silverkorn** [comment] 2017-03-10 17:35
Hmm... I thought that burst was about a buffering feature that by lowering it, it would start faster on the listener's end.

Unfortunately, the correlation that it worked properly on 2.4.0-kh and not on 2.4.2 with the same configuration file and this only happens on Windows 7 (SP1) OS, on any Web browsers (IE11, Chrome, Firerox). 
Windows XP SP3 (Any browsers) and Windows 10 (Tested on Firefox & Chrome) were tested on 2.4.2 and it worked properly...

[__Not working__] Any server using Icecast __2.4.2__ or __2.4.0__
http://cyberjamz.com:8000/SV1.MP3 (audio/mpeg - 96kbps - 32000 Hz)
http://audio.telpin.com.ar/energy (audio/mpeg - 24 kbps - 22050 Hz)
http://icecast.omroepvenray.nl/lov.mp3 (audio/mpeg - 128 kbps - 44100 Hz)
http://bogo.audio:8000/asylumrock (audio/aacp - 96 kbps - 44100 Hz)
http://gnusocial.net:8000/tvelbinario.ogg (application/ogg - 80 kbps - 44100 Hz [Has video stream])

[__Working__] Any server using Icecast __2.4.0-kh#__
http://streaming.megatopradio.com/megatopradio_autodj (audio/mpeg - 128 kbps - 44100 Hz)
http://netstream.lifeonline.fm/CJLF/128mp3 (audio/mpeg  - 128 kbps - 44100 Hz)
http://icecast.wildghosts.com:8000/Christmas128 (audio/mpeg - 128 kbps - 44100 Hz)
http://filthybass.net/live1 (audio/mpeg - 112 kbps - 44100 Hz)

[__Note__] Any _audio/aacp_ and _audio/aac_ has the __same reaction__ on __2.4.0-kh#__ than the __2.4.2__/__2.4.0__ Icecast:
http://199.180.75.26/stream (audio/aacp - 64 kbps - 44100 Hz)
http://streams.olympia-radio.nl/olympia64 (audio/aac - 96 kbps - 32000 Hz)

At first I thought it would be because of the network but I tried on a direct access to the Internet without proxies/firewalls and the same behaviour happened.

As by relating the issue #8, I was guessing that it might be a problem through a HTTP header that Windows 7 SP1 might not operate properly under any browsers.

Hope this helps.
Thanks!

**Comment by ePirat** [comment] 2018-03-19 21:27
Closing this as I am unable to reproduce and so far this is the only report we got about this.
Note that neither MP3 nor AAC are officially supported formats so it could be that it works better in kh.

**Closed by ePirat** 2018-03-19 21:27 UTC
Labels: invalid
