### ISSUE TITLE
Relay in master-slave mode should use basic auth when streaming mounts from master

### ISSUE THREAD

**Issue by spr0cketeer** [xiph/Icecast-Server#17] opened 2017-11-17 23:35 UTC
server is git master c1b4e75509903b4bfbcc26d494ceb2cc2e90d4db

I have a relay in master-slave mode relaying master mounts which are all url auth protected

The relay grabs the list of mounts from master ok using basic auth from config file relay options `<master-username>/<master-password>` 

It then tries to connect to the master mounts as a listener but it's not using basic auth for this stage so the url auth performed by master fails, as the POST info it sends to `<listener_add>` url contains blank user and pass fields so no way to auth the request.

Looks like it uses basic auth when using a relay in single-broadcast mode:
https://github.com/xiph/Icecast-Server/blob/master/src/slave.c#L172

but not when using master-slave mode.

**Comment by dm8tbr** [comment] 2019-01-03 16:35
Duplicate of https://gitlab.xiph.org/xiph/icecast-server/issues/1860

**Closed by dm8tbr** 2019-01-03 16:35 UTC
